2 feat create a splash screen
WeAppe-ar/frontend-old pull request #9
Opened 2022-09-10 00:54 UTC by Gomez-Enzo

2022-09-10 14:49 UTC, NazarenoCavazzon requested changes

2022-09-10 14:49 UTC, NazarenoCavazzon commented on pubspec.yaml
> +    - assets/logo.png
create a new folder called images and put into it the logo.

Then change this line to `- assets/images/`

2022-09-11 02:52 UTC, tomassasovsky requested changes

2022-09-11 02:52 UTC, tomassasovsky commented on pubspec.yaml
> +  flutter_native_splash: ^2.2.9
i think this should be a dev dependency, no?

2022-09-12 17:19 UTC, NazarenoCavazzon approved these changes
LGTM

2022-09-12 17:19 UTC, NazarenoCavazzon commented on pubspec.yaml
> +  flutter_native_splash: ^2.2.9
Yep, @Gomez-Enzo move this dependency to the dev ones

2022-09-12 17:45 UTC, tomassasovsky approved these changes
LGTM! 
![tomi approves](https://user-images.githubusercontent.com/63405252/189721319-04977fde-15c1-4749-a12e-463e5c02f3f6.jpeg)

2022-09-12 17:45 UTC, merged